name = "frago"
license = "MIT"
licenselink = "https://github.com/lowdit/frago/blob/master/LICENSE"
description = "Tool for a French governemental Reports for Accessibility compliance with goHugo"
homepage = "https://github.com/lowdit/frago/"
tags = ["audits", "accessibility", "compliance","RGAA","quality","front-end"]
min_version = 0.8
theme_version = "1.13.2"

[author]
  name = "Bertrand Keller"
  homepage = "https://github.com/bertrandkeller"
